//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientDemoWS.DemoRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://student-test.org")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string addressField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string address {
            get {
                return this.addressField;
            }
            set {
                if ((object.ReferenceEquals(this.addressField, value) != true)) {
                    this.addressField = value;
                    this.RaisePropertyChanged("address");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://student-test.org", ConfigurationName="DemoRef.DemoWebServiceSoap")]
    public interface DemoWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name name from namespace http://student-test.org is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://student-test.org/addStudent", ReplyAction="*")]
        ClientDemoWS.DemoRef.addStudentResponse addStudent(ClientDemoWS.DemoRef.addStudentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://student-test.org/addStudent", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientDemoWS.DemoRef.addStudentResponse> addStudentAsync(ClientDemoWS.DemoRef.addStudentRequest request);
        
        // CODEGEN: Generating message contract since element name getAllResult from namespace http://student-test.org is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://student-test.org/getAll", ReplyAction="*")]
        ClientDemoWS.DemoRef.getAllResponse getAll(ClientDemoWS.DemoRef.getAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://student-test.org/getAll", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientDemoWS.DemoRef.getAllResponse> getAllAsync(ClientDemoWS.DemoRef.getAllRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addStudentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addStudent", Namespace="http://student-test.org", Order=0)]
        public ClientDemoWS.DemoRef.addStudentRequestBody Body;
        
        public addStudentRequest() {
        }
        
        public addStudentRequest(ClientDemoWS.DemoRef.addStudentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://student-test.org")]
    public partial class addStudentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string address;
        
        public addStudentRequestBody() {
        }
        
        public addStudentRequestBody(string name, string address) {
            this.name = name;
            this.address = address;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addStudentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addStudentResponse", Namespace="http://student-test.org", Order=0)]
        public ClientDemoWS.DemoRef.addStudentResponseBody Body;
        
        public addStudentResponse() {
        }
        
        public addStudentResponse(ClientDemoWS.DemoRef.addStudentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://student-test.org")]
    public partial class addStudentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int addStudentResult;
        
        public addStudentResponseBody() {
        }
        
        public addStudentResponseBody(int addStudentResult) {
            this.addStudentResult = addStudentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAll", Namespace="http://student-test.org", Order=0)]
        public ClientDemoWS.DemoRef.getAllRequestBody Body;
        
        public getAllRequest() {
        }
        
        public getAllRequest(ClientDemoWS.DemoRef.getAllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getAllRequestBody {
        
        public getAllRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllResponse", Namespace="http://student-test.org", Order=0)]
        public ClientDemoWS.DemoRef.getAllResponseBody Body;
        
        public getAllResponse() {
        }
        
        public getAllResponse(ClientDemoWS.DemoRef.getAllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://student-test.org")]
    public partial class getAllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientDemoWS.DemoRef.Student[] getAllResult;
        
        public getAllResponseBody() {
        }
        
        public getAllResponseBody(ClientDemoWS.DemoRef.Student[] getAllResult) {
            this.getAllResult = getAllResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DemoWebServiceSoapChannel : ClientDemoWS.DemoRef.DemoWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DemoWebServiceSoapClient : System.ServiceModel.ClientBase<ClientDemoWS.DemoRef.DemoWebServiceSoap>, ClientDemoWS.DemoRef.DemoWebServiceSoap {
        
        public DemoWebServiceSoapClient() {
        }
        
        public DemoWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DemoWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DemoWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DemoWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientDemoWS.DemoRef.addStudentResponse ClientDemoWS.DemoRef.DemoWebServiceSoap.addStudent(ClientDemoWS.DemoRef.addStudentRequest request) {
            return base.Channel.addStudent(request);
        }
        
        public int addStudent(string name, string address) {
            ClientDemoWS.DemoRef.addStudentRequest inValue = new ClientDemoWS.DemoRef.addStudentRequest();
            inValue.Body = new ClientDemoWS.DemoRef.addStudentRequestBody();
            inValue.Body.name = name;
            inValue.Body.address = address;
            ClientDemoWS.DemoRef.addStudentResponse retVal = ((ClientDemoWS.DemoRef.DemoWebServiceSoap)(this)).addStudent(inValue);
            return retVal.Body.addStudentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientDemoWS.DemoRef.addStudentResponse> ClientDemoWS.DemoRef.DemoWebServiceSoap.addStudentAsync(ClientDemoWS.DemoRef.addStudentRequest request) {
            return base.Channel.addStudentAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientDemoWS.DemoRef.addStudentResponse> addStudentAsync(string name, string address) {
            ClientDemoWS.DemoRef.addStudentRequest inValue = new ClientDemoWS.DemoRef.addStudentRequest();
            inValue.Body = new ClientDemoWS.DemoRef.addStudentRequestBody();
            inValue.Body.name = name;
            inValue.Body.address = address;
            return ((ClientDemoWS.DemoRef.DemoWebServiceSoap)(this)).addStudentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientDemoWS.DemoRef.getAllResponse ClientDemoWS.DemoRef.DemoWebServiceSoap.getAll(ClientDemoWS.DemoRef.getAllRequest request) {
            return base.Channel.getAll(request);
        }
        
        public ClientDemoWS.DemoRef.Student[] getAll() {
            ClientDemoWS.DemoRef.getAllRequest inValue = new ClientDemoWS.DemoRef.getAllRequest();
            inValue.Body = new ClientDemoWS.DemoRef.getAllRequestBody();
            ClientDemoWS.DemoRef.getAllResponse retVal = ((ClientDemoWS.DemoRef.DemoWebServiceSoap)(this)).getAll(inValue);
            return retVal.Body.getAllResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientDemoWS.DemoRef.getAllResponse> ClientDemoWS.DemoRef.DemoWebServiceSoap.getAllAsync(ClientDemoWS.DemoRef.getAllRequest request) {
            return base.Channel.getAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientDemoWS.DemoRef.getAllResponse> getAllAsync() {
            ClientDemoWS.DemoRef.getAllRequest inValue = new ClientDemoWS.DemoRef.getAllRequest();
            inValue.Body = new ClientDemoWS.DemoRef.getAllRequestBody();
            return ((ClientDemoWS.DemoRef.DemoWebServiceSoap)(this)).getAllAsync(inValue);
        }
    }
}
